version: '3.8'

services:
  # 1. Service Database PostgreSQL
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dev_adhi
      POSTGRES_PASSWORD: Jakarta191004
      # Diubah menggunakan underscore agar aman dari error query
      POSTGRES_DB: nutricca_db 
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # 2. Service AI Python
  ai-api:
    build: 
      context: ./ai-api
    # Tambahan image tag untuk sinkronisasi Docker Hub
    image: stevevaijohnpettruci/nutricca-ai:latest
    ports:
      - "8000:8000"
    volumes:
      - ./ai-api:/app 

  # 3. Service Backend Node.js
  backend-api:
    build: 
      context: ./back-end
    # Tambahan image tag untuk sinkronisasi Docker Hub
    image: stevevaijohnpettruci/nutricca-be:latest
    ports:
      - "3000:3000"
    volumes:
      - ./back-end:/app
      - /app/node_modules
      - ./ai-api/app/artifacts:/ai-service/artifacts
    command: npm run start:dev
    environment:
      DB_USER: dev_adhi
      DB_PASSWORD: Jakarta191004
      DB_HOST: database
      # Harus sama dengan POSTGRES_DB di atas
      DB_NAME: nutricca_db 
      DB_PORT: 5432
    depends_on:
      - database
      - ai-api

  # 4. Service Frontend React/Vite
  frontend-app:
    build:
      context: ./front-end
    # Opsional: Jika frontend juga mau di-push ke Docker Hub nantinya
    image: stevevaijohnpettruci/nutricca-fe:latest
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    depends_on:
      - backend-api

volumes:
  # Diperbaiki menjadi format YAML yang valid
  pg_data: